apiVersion: batch/v1
kind: Job
metadata:
  name: r3kvload
  namespace: r3
spec:
  completions: $N_JOBS
  parallelism: $N_JOBS
  template:
    spec:
      containers:
      - name: r3kvload
        image: r3musketeers/r3kvload:latest
        resources:
          requests:
            cpu: 4
          limits:
            cpu: 8
          # requests:
          #   memory: 100Mi
          # limits:
          #   memory: 200Mi
        # command: [ "/bin/r3kvload", "-d", "2m", "-u", "http://10.244.2.5:11010/kv" ]
        args: [ "-u", "http://$SERVER_POD_IP:11010/kv", "-d", "2m", "-c", "$EXTRA_THREADS", "-s", "$SLEEP_DURATION" ]
      restartPolicy: Never
      nodeSelector:
        role: client
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "r3kvload" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
  backoffLimit: 4